[package]
name = "sway-colord"
version = "0.1.0"
authors = ["David Karrick <the.white.wolf.is.1337@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ron = "0.6.4"
xdg = "^2.1"
serde = { version = "1.0.60", features = ["serde_derive"] }
chrono = "0.4.19"
swayipc-async = "2.0.0-alpha.2"
async-std = { version = "1", features = ["attributes"]}
async-recursion = "0.3.1"
anyhow = "1.0.37"
once_cell = "1.5.2"