on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*'

name: Create Release

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - 1.49.0  # MSRV

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/release
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: System dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc
          mkdir -p ~/.cargo/release
          
      - name: Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt, clippy

      - name: Build
        run: cargo build --release && strip target/release/sway-colord

      - name: Upload binary to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/sway-colord
          asset_name: sway-colord-${{ github.event.release.tag_name }}-x86_64
          tag: ${{ github.ref }}
          overwrite: true

      - name: Create Debian package
        run: |
          mkdir -p ~/sway-colord-deb/DEBIAN
          cp build-os/debian/control ~/sway-colord-deb/DEBIAN/
          echo "Version: ${{ github.event.release.tag_name }}" >> ~/sway-colord-deb/DEBIAN/control
          cp build-os/debian/postinst $(DESTDIR)/DEBIAN/
          chmod 775 ~/sway-colord-deb/DEBIAN/postinst
          dpkg-deb --build ~/sway-colord-deb sway-colord-${{ github.event.release.tag_name }}-x86_64.deb
          md5sum sway-colord-${{ github.event.release.tag_name }}-x86_64.deb > sway-colord-${{ github.event.release.tag_name }}-x86_64.deb.md5sum
      - name: Upload Debian release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: '${{ github.event.release.upload_url }}'
          asset_path: 'sway-colord-${{ github.event.release.tag_name }}-x86_64.deb'
          asset_name: 'sway-colord-${{ github.event.release.tag_name }}-x86_64.deb'
          asset_content_type: application/octet-stream

      - name: Upload Debian release checksum
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: '${{ github.event.release.upload_url }}'
          asset_path: 'sway-colord-${{ github.event.release.tag_name }}-x86_64.deb.md5sum'
          asset_name: 'sway-colord-${{ github.event.release.tag_name }}-x86_64.deb.md5sum'
          asset_content_type: text/plain

  arch:
    runs-on: ubuntu-latest
    needs: [ci]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare arch package metadata
        run: |
          MD5_SUM=$(md5sum target/release/sway-colord | awk '{print $1}')
          awk -v q="'" -v MD5_SUM=$MD5_SUM -i inplace 'BEGINFILE{print "md5sums=(" q MD5_SUM q ")"}{print}' build-os/arch/sway-colord/PKGBUILD
          awk -i inplace 'BEGINFILE{print "pkgver=${{ github.event.release.tag_name }}"}{print}' build-os/arch/sway-colord/PKGBUILD
      - name: Validate PKGBUILD
        id: validate-pkgbuild
        uses: grumlimited/arch-pkgbuild-builder@b0f22da174699e6795f4434f252e15e6c8265b9e
        with:
          debug: true
          target: pkgbuild
          pkgname: build-os/arch/sway-colord/

      - name: Create arch package checksum file
        run: |
          sudo chown -R $USER .
          md5sum build-os/arch/sway-colord/*.zst >> build-os/arch/sway-colord/sway-colord-${{ github.event.release.tag_name }}-1-x86_64.pkg.tar.zst.md5sum
      - name: Upload Arch Linux release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: '${{ github.event.release.upload_url }}'
          asset_path: 'build-os/arch/sway-colord/sway-colord-${{ github.event.release.tag_name }}-1-x86_64.pkg.tar.zst'
          asset_name: 'sway-colord-${{ github.event.release.tag_name }}-1-x86_64.pkg.tar.zst'
          asset_content_type: application/octet-stream

      - name: Upload Arch Linux release checksum
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: '${{ github.event.release.upload_url }}'
          asset_path: 'build-os/arch/sway-colord/sway-colord-${{ github.event.release.tag_name }}-1-x86_64.pkg.tar.zst.md5sum'
          asset_name: 'sway-colord-${{ github.event.release.tag_name }}-1-x86_64.pkg.tar.zst.md5sum'
          asset_content_type: text/plain